# Generated by Django 5.2 on 2025-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='sleep_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='water_liters',
            field=models.FloatField(default=0.0),
        ),
    ]
